# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c968922f74f1f9813f129ae346efe111392682da5a771f667eae5a5f7c4112d51f9a23bc8a97036c94314c1b189435f05d6e6f32006c3321c9da04f4ff9b6b

test:
  secret_key_base: 08c3d2b7a0535e2eab64354c9640d1162cf06f1df6689087ac0dcd0742d157afdf2776666c31566db51b105c8b1794c37aa3ac90219ea0dbfaca2f6022da63e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
